name: Daily Tracker CSV Only

on:
  schedule:
    - cron: '0 0 * * *'  # 9:00 JST
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y chromium-driver
          pip install -r requirements.txt

      - name: Run script
        run: python main.py
